# Generated by Django 5.2.8 on 2025-11-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Processando', 'Processando'), ('Enviado', 'Enviado')], default='Pendente', max_length=20),
        ),
    ]
