# Generated by Django 5.2.8 on 2026-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEasy', '0002_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Novo', 'novo'), ('Seminovo', 'seminovo'), ('Usado', 'usado')], default='Novo', max_length=50),
        ),
    ]
