# Generated by Django 5.2.8 on 2025-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEasy', '0003_cart_deleted_at_cartitem_deleted_at_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
